export const perfTitle = [
  '流量(m3/s)',
  '压力(Pa)',
  '静压(Pa)',
  '风机效率(%)',
  '静压效率(%)',
  '轴功率(kW)',
  '转速(r/min)',
  '直径(mm)',
  '噪音(dB(A))',
  '比转速',
  'u',
  '流量系数',
  '压力系数',
];
export const perfDataIndex = [
  // 'model_id'  '型号',
  'flowRate',
  'fullPressure',
  'staticPressure',
  'fanEff',
  'staticPressureEff',
  'shaftPower',
  'motorSpeed',
  'impellerDiameter',
  'noise',
  'specificSpeed',
  'u',
  'flowCoefficient',
  'pressureCoefficient',
];
export const excelTableColumns = {
  '流量(m3/s)': 'flowRate',
  '压力(Pa)': 'fullPressure',
  '静压(Pa)': 'staticPressure',
  '风机效率(%)': 'fanEff',
  '静压效率(%)': 'staticPressureEff',
  '轴功率(kW)': 'shaftPower',
  '转速(r/min)': 'motorSpeed',
  '直径(mm)': 'impellerDiameter',
  '噪音(dB(A))': 'noise',
  比转速: 'specificSpeed',
  u: 'u',
  流量系数: 'flowCoefficient',
  压力系数: 'pressureCoefficient',
};
