//  顺序对应改成字典
export const title = [
  '应用车型大类',
  '应用车型',
  '冷却对象',
  '风机类型',
  '风机型号',
  '图号',
  '版本号',
  '流量(m3/s)',
  '全压(Pa)',
  '静压(Pa)',
  '效率(%)',
  '轴功率(kW)',
  '叶轮直径(mm)',
  '重量(Kg)',
  '电机型号',
  '电源频率(Hz)',
  '电机功率(kW)',
  '转速(r/min)',
  '额定电压(V)',
  '额定电流(A)',
  '海拔(m)',
  '温度(℃)',
  '湿度(%)',
  '备注1(项目名称)',
  '备注2(客户)',
];
export const dataIndex = [
  'applicationModelId',
  'applicationModel',
  'coolObject',
  'category', //=>categoryId category
  'model',
  'figNum',
  'version',
  'flowRate',
  'fullPressure',
  'staticPressure',
  'efficiency',
  'shaftPower',
  'impellerDiameter',
  'weight',
  'motorModel',
  'powerFrequency',
  'motorPower',
  'motorSpeed',
  'ratedVoltage',
  'ratedCurrent',
  'altitude',
  'humidity',
  'temperature',
  'remark1',
  'remark2',
];

export const excelTableColumns: {} = {
  应用车型大类: 'applicationModelId',
  应用车型: 'applicationModel',
  冷却对象: 'coolObject',
  风机类型: 'category', //=>categoryId category
  风机型号: 'model',
  图号: 'figNum',
  版本号: 'version',
  '流量(m3/s)': 'flowRate',
  '全压(Pa)': 'fullPressure',
  '静压(Pa)': 'staticPressure',
  '效率(%)': 'efficiency',
  '轴功率(kW)': 'shaftPower',
  '叶轮直径(mm)': 'impellerDiameter',
  '重量(Kg)': 'weight',
  电机型号: 'motorModel',
  '电源频率(Hz)': 'powerFrequency',
  '电机功率(kW)': 'motorPower',
  '转速(r/min)': 'motorSpeed',
  '额定电压(V)': 'ratedVoltage',
  '额定电流(A)': 'ratedCurrent',
  '海拔(m)': 'altitude',
  '温度(℃)': 'temperature',
  '湿度(%)': 'humidity',
  '备注1(项目名称)': 'remark1',
  '备注2(客户)': 'remark2',
};
